export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
//login type
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const SAVE_EMAIL_STORE = "SAVE_EMAIL_STORE";
//register types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
//confirm email
export const SEND_EMAIL_DELETE = 'SEND_EMAIL_DELETE';
export const SEND_SUCCESS_EMAIL = 'SEND_SUCCESS_EMAIL';
export const EMAIL_CONFIRM_ERROR = 'EMAIL_CONFIRM_ERROR';
export const EMAIL_CONFIRM_REQUEST = 'EMAIL_CONFIRM_REQUEST';
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS';
//get companies types
export const COMPANIES_LOAD_REQUEST = 'COMPANIES_LOAD_REQUEST';
export const COMPANIES_LOADED_SUCCESS = 'COMPANIES_LOAD_SUCCESS';
export const COMPANIES_LOADED_ERROR = 'COMPANIES_LOAD_ERROR';
//company types
export const COMPANY_LOAD_REQUEST = 'COMPANY_LOAD_REQUEST';
export const COMPANY_LOADED_SUCCESS = 'COMPANY_LOAD_SUCCESS';
export const SAVE_COMPANY_REGISTER = 'SAVE_COMPANY_REGISTER';
export const COMPANY_LOADED_ERROR = 'COMPANY_LOAD_ERROR';
//reviews load types
export const REVIEWS_LIST_LOAD_REQUEST = 'REVIEWS_LIST_LOAD_REQUEST';
export const REVIEWS_LIST_LOADED_SUCCESS = 'REVIEWS_LIST_LOAD_SUCCESS';
export const REVIEWS_LIST_LOADED_ERROR = 'REVIEWS_LIST_LOAD_ERROR';
//review create types
export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATED_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATED_ERROR = 'REVIEW_CREATE_ERROR';
//user types
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';
//user edit profile types
export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDITED_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDITED_ERROR = 'USER_EDIT_ERROR';
//error types
export const ERRORS_GET = 'ERRORS_GET';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';
//order create types
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATED_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATED_ERROR = 'ORDER_CREATE_ERROR';
export const ORDER_SAVE_STORE = 'ORDER_SAVE_STORE';
//order load type
export const ORDER_LOADED_ERROR = 'ORDER_LOAD_ERROR';
export const ORDER_LOAD_REQUEST = 'ORDER_LOAD_REQUEST';
export const ORDER_LOADED_SUCCESS = 'ORDER_LOAD_SUCCESS';
//orders list types
export const ORDERS_LIST_LOAD_REQUEST = 'ORDERS_LIST_LOAD_REQUEST';
export const ORDERS_LIST_LOADED_SUCCESS = 'ORDERS_LIST_LOAD_SUCCESS';
export const ORDERS_LIST_LOADED_ERROR = 'ORDERS_LIST_LOAD_ERROR';
//oder change status
export const ORDER_UPDATED_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATED_STATUS_ERROR = 'ORDER_UPDATE_STATUS_ERROR';
export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
//admin load list users or companies
export const LIST_CONTROL_LOAD_REQUEST =  'LIST_CONTROL_LOAD_REQUEST'
export const LIST_CONTROL_LOADED_SUCCESS =  'LIST_CONTROL_LOAD_SUCCESS'
export const LIST_CONTROL_LOADED_ERROR =  'LIST_CONTROL_LOAD_ERROR';